name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
    
env:
  WHO_TO_GREET: "${{ inputs.who-to-greet }}"
  
runs:
  using: 'composite'
  steps:
  - uses: swift-actions/setup-swift@v1.25.0
    with:
      swift-version: "5.9"
  - name: Get swift version
    run: swift --version
    shell: bash
  - name: Build
    run: swift build --package-path "${{ github.action_path }}"
    shell: bash
  - name: Run
    run: swift run --package-path "${{ github.action_path }}"
    shell: bash
    

